FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["DockerCoreApp.csproj", "DockerCoreApp.csproj"]
RUN dotnet restore "DockerCoreApp.csproj"
COPY . .
RUN dotnet build "DockerCoreApp.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "DockerCoreApp.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "DockerCoreApp.dll"]